// Run only in the disposable wbc-wp installation. All mail is suppressed by the test observer.
const {chromium}=require('playwright');const assert=require('assert');const {execFileSync}=require('child_process');
const wp=(...args)=>execFileSync('docker',['exec','wbc-wp','php','/tmp/wp-cli.phar',...args,'--allow-root'],{encoding:'utf8'}).trim();
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const p=await b.newPage({viewport:{width:1280,height:900}});const errors=[];p.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:8088';const username='wbc-browser-'+Date.now();const email=username+'@example.invalid';let uid;const registration=wp('option','get','users_can_register');try{
 wp('option','update','users_can_register','1');
 await p.goto(base+'/learn/?lesson=L-01.1');await p.getByRole('button',{name:'Mark this lesson as read',exact:true}).click();await p.getByText('Reading progress saved.',{exact:false}).waitFor();await p.getByLabel('Remember my progress on this device').check();
 await p.goto(base+'/wp-login.php?action=register');await p.getByLabel('Username',{exact:true}).fill(username);await p.getByLabel('Email',{exact:true}).fill(email);await p.getByRole('button',{name:'Register',exact:true}).click();await p.getByText('Registration complete.',{exact:false}).waitFor();uid=wp('user','get',username,'--field=ID');assert.equal(wp('user','get',uid,'--field=roles'),'subscriber');
 const messages=JSON.parse(execFileSync('docker',['exec','wbc-wp','cat','/tmp/wbc-test-mails.json'],{encoding:'utf8'}));const reset=messages.find(m=>m.message.includes('action=rp')&&JSON.stringify(m.to).includes(email));assert(reset,'Registration produces a password-setup email');const resetUrl=reset.message.match(/http:\/\/127\.0\.0\.1:8088[^\s<>]+/g).find(url=>url.includes('action=rp')).replace(/&amp;/g,'&');await p.goto(resetUrl);await p.waitForFunction(()=>{const input=document.querySelector('#pass1');return input && input.value.length>=16 && input.type==='text';});const password=await p.locator('#pass1').inputValue();assert(password.length>=16,'Core WordPress provides a generated password');await p.getByRole('button',{name:'Save Password',exact:true}).click();await p.getByText('Your password has been reset.',{exact:false}).waitFor();
 await p.goto(base+'/wp-login.php?redirect_to='+encodeURIComponent(base+'/journey/'));await p.locator('#user_login').fill(username);await p.locator('#user_pass').fill(password);await p.getByRole('button',{name:'Log In',exact:true}).click();await p.getByText('Your journey is saved in your account.',{exact:false}).waitFor();await p.getByLabel('completion · L-01.1',{exact:true}).check();p.once('dialog',d=>d.accept());await p.getByRole('button',{name:'Save device progress to this account',exact:true}).click();await p.getByText('Import completed.',{exact:false}).waitFor();
 await p.goto(base+'/articles/');await p.getByRole('button',{name:'Why a stablecoin can still surprise you',exact:true}).click();await p.getByRole('button',{name:'Save article',exact:true}).click();await p.getByRole('button',{name:'Unsave article',exact:true}).waitFor();await p.goto(base+'/saved/');await p.getByRole('button',{name:'Why a stablecoin can still surprise you',exact:true}).click();await p.getByRole('button',{name:'Unsave article',exact:true}).click();await p.getByText('No saved articles yet.',{exact:false}).waitFor();
 await p.goto(base+'/wp-login.php?action=lostpassword');await p.locator('#user_login').fill(email);await p.getByRole('button',{name:'Get New Password',exact:true}).click();await p.getByText('Check your email',{exact:false}).first().waitFor();const recovery=JSON.parse(execFileSync('docker',['exec','wbc-wp','cat','/tmp/wbc-test-mails.json'],{encoding:'utf8'}));assert(recovery.length>messages.length,'Password recovery generates an email');await p.goto(base+'/journey/');await p.getByRole('link',{name:'Sign out',exact:true}).click();await p.getByRole('link',{name:'Sign in',exact:true}).waitFor();assert.deepEqual(errors,[]);console.log('PASS local accounts: subscriber registration, password-setup link, login, explicit guest import, bookmark/save list/unsave, recovery email generation and logout; all outbound mail suppressed.');
}catch(e){await p.screenshot({path:'/tmp/wbc-account-failure.png'});console.error('Account test state:',new URL(p.url()).pathname,await p.locator('#login_error,.wbc-status').allTextContents());throw e;}finally{if(!uid){try{uid=wp('user','get',username,'--field=ID')}catch{}}if(uid)wp('user','delete',uid,'--yes');wp('option','update','users_can_register',registration);await b.close();}})().catch(e=>{console.error(e.message);process.exit(1)});
