const {chromium}=require('playwright');const assert=require('assert');const fs=require('fs');const path=require('path');
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const p=await b.newPage({viewport:{width:1487,height:1058}});const errors=[];p.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:8088';const out=path.resolve(__dirname,'../design-evidence');fs.mkdirSync(out,{recursive:true});try{
 await p.goto(base+'/');await p.evaluate(()=>document.fonts.ready);assert.equal(await p.locator('.wbc-hero').count(),1);assert(!(await p.locator('body').innerText()).includes('Lorem ipsum'));assert.equal(await p.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('link').count(),5);await p.locator('footer').scrollIntoViewIfNeeded();assert(await p.locator('main img').evaluateAll(xs=>xs.every(x=>x.complete&&x.naturalWidth>0)));await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:path.join(out,'home-desktop.png')});
 for(const slug of ['learn','articles','topics','glossary','journey','saved','practice']){const response=await p.goto(base+'/'+slug+'/');assert.equal(response.status(),200);if(await p.locator('.wbc-app').count())await p.getByText('Your learning space is ready.',{exact:false}).waitFor();assert.equal(await p.locator('h1').count(),1);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(['articles','topics'].includes(slug)){await p.locator('footer').scrollIntoViewIfNeeded();assert(await p.locator('main img').evaluateAll(xs=>xs.every(x=>x.complete&&x.naturalWidth>0)));await p.evaluate(()=>scrollTo(0,0));}if(['articles','topics','journey','practice'].includes(slug))await p.screenshot({path:path.join(out,slug+'-desktop.png')});}
 await p.goto(base+'/learn/?lesson=L-01.1');await p.getByRole('button',{name:'Next lesson',exact:true}).click();assert(p.url().includes('lesson=L-01.2'));await p.getByRole('button',{name:'Previous lesson',exact:true}).click();assert(p.url().includes('lesson=L-01.1'));await p.getByRole('searchbox').fill('a completely absent phrase');await p.getByText('No matching published content.',{exact:false}).waitFor();
 await p.goto(base+'/articles/?article=A-EX-01');await p.getByRole('link',{name:'Sign in to save this article',exact:true}).waitFor();await p.setViewportSize({width:375,height:812});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.goto(base+'/');await p.getByRole('button',{name:'Menu',exact:true}).click();assert.equal(await p.getByRole('button',{name:'Menu',exact:true}).getAttribute('aria-expanded'),'true');await p.keyboard.press('Escape');assert.equal(await p.getByRole('button',{name:'Menu',exact:true}).getAttribute('aria-expanded'),'false');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Menu');await p.screenshot({path:path.join(out,'home-mobile.png'),fullPage:true});
 for(const slug of ['learn','articles','topics','glossary','journey','saved','practice']){await p.goto(base+'/'+slug+'/');if(await p.locator('.wbc-app').count())await p.getByText('Your learning space is ready.',{exact:false}).waitFor();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(['articles','learn'].includes(slug))await p.screenshot({path:path.join(out,slug+'-mobile.png')});}
 const missing=await p.goto(base+'/this-page-does-not-exist/');assert.equal(missing.status(),404);await p.getByRole('heading',{name:'This page has moved or is unavailable.',exact:true}).waitFor();assert.equal(await p.locator('#wbc-main-nav').count(),1);await p.goto(base+'/wp-login.php');assert.equal(await p.locator('#login h1 a').textContent(),'Wetin Be Crypto');await p.screenshot({path:path.join(out,'login-mobile.png')});assert.deepEqual(errors,[]);console.log('PASS presentation browser: illustrated homepage, loaded assets, curated navigation, seven routes, previous/next lessons, empty search, article deep link/sign-in, mobile Menu/Escape/focus, mobile no overflow, branded 404 and login, zero page errors.');
}finally{await b.close();}})().catch(e=>{console.error(e.message);process.exit(1)});
